### ISSUE TITLE
Unable to set require_signature_auth in template

### ISSUE THREAD

**Issue by joel31415** [transloadit/terraform-provider-transloadit#20]
Hi,
As far as I can tell there's no way to set `require_signature_auth` in my `transloadit_template`, right now I need to make an additional API call outside of this provider to require it.

As a side note, I ran into some issues getting the provider to work following using instructions in README.md (with terraform 0.13.3), but adding this makes it so that the provider is automatically installed etc. on `terraform init`:
```
terraform {
  required_providers {
    transloadit = {
      source  = "transloadit/transloadit"
      version = "0.2.0"
    }
  }
}
```

**Comment by kvz** [comment]
Thanks for the report! We'll look into this :ok_hand:

**Comment by kvz** [comment]
@Etienne-Carriere did you see this report? Could you take a look?

**Comment by Etienne-Carriere** [comment]
@kvz, thank you for the reminder. I see it last week but forgot to answer. 
We will need first to update https://github.com/transloadit/go-sdk to add require_signature_auth argument . PR is coming !

**Comment by kvz** [comment]
Hi there, we just fixed this issue! Thank you again for reporting :heart:
