### ISSUE TITLE
Using HCL for Template bodies instead of JSON?

### ISSUE THREAD

**Issue by kvz** [transloadit/terraform-provider-transloadit#25]
Currently for Templates we use this:

```
resource "transloadit_template" "resize-img" {
	name     = "resize-img"
	template = <<EOT
{
  "steps": {
    "imported": {
      "robot": "/s3/import",
      "credentials": "my_s3_$${assembly.region}",
      "path": "/onthefly/$${fields.input}"
    },
    "resized": {
      "use": "imported",
      "robot": "/image/resize",
      "width": "$${fields.w}",
      "imagemagick_stack": "v2.0.7"
    },
    "served": {
      "use": "resized",
      "robot": "/file/serve"
    }
  }
}
EOT
}
```

I wonder if it would be possible somehow, to use HCL to write Templates instead, since it can map back to JSON? 

Not unlike an `iam_policy_document` policy document i suppose https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/iam_policy_document

Or maybe there is some native way where we can tell Terraform: hey this hcl right here can be turned into a JSON string right there?

Main reason: DX. Examples and config files are going to look prettier, you can comment Templates, no longer have trailing comma issues, nicer syntax highlighting.

**Comment by Etienne-Carriere** [comment]
If we take [iam_policy_docment](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_iam_policy_document.go#L57-L103), we see that we need to describe the full schema. Moreover, the schema description in terraform don't allow to define a polymorphic argument. 

For the template schema, I search but I don't find the official Template schema . If I remember well, in steps, the field use can be of multiple types : scalar, array and map (was my research in 2020). 

With this constraint it seems difficult for me to have a full schema description in templates. 

Open to discuss,

**Comment by kvz** [comment]
Ah right, you had brought up this concern before, pasting your comments for convenience:

> * In the template 'steps' definitions, there is an issue with the "use" parameter that can have multiple type (scalar, array or object)
> * In terraform, it will not be possible to have this logic. One solution is to have 2 parameters (exclusive each other) : use (array that will handle scalar and array) and use_map

The other things can be fixed (we can provide a schema, etc). But `use_map` is a bit of a dealbreaker i think. Because people will eventually try to use use_map in JSON and get confused.

So I'll close this issue again, thank you for sharing all the details around this again 🙏
