### ISSUE TITLE
Migrate away from travis CI ? 

### ISSUE THREAD

**Issue by Etienne-Carriere** [transloadit/terraform-provider-transloadit#26]
* Do we have/want to migrate away from travis CI (due to change in free policy : https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) to other solution ? 
* Which other solution to choose ? Github Actions ?

For Github Actions, we need 2 jobs : 
- [x]   CI job : test (unit + acceptance) + build providers for different targets : https://github.com/transloadit/terraform-provider-transloadit/blob/master/.github/workflows/ci.yml
- [x]  Release Job : Integrate goreleaser and gpg logic in a github action : I think what could be difficult is the integration of GPG key : https://github.com/transloadit/terraform-provider-transloadit/blob/master/.github/workflows/release.yml

**Comment by kvz** [comment]
Hi Etienne, yes we have been gradually moving all projects to GitHub actions, we should do it for this project too. Is this something you have idle cycles for? I could probably also do most of it myself if not 👌

**Comment by Etienne-Carriere** [comment]
Hi Kevin,

* For CI, could you please add 2 env variables for acceptance tests : 
  * TRANSLOADIT_AUTH_KEY
  * TRANSLOADIT_AUTH_SECRET 
* For Release, I made a draft version with release but just without the gpg signing part : 
  * Workflow : https://github.com/transloadit/terraform-provider-transloadit/blob/master/.github/workflows/release.yml
  * Example : https://github.com/transloadit/terraform-provider-transloadit/runs/3230173449?check_suite_focus=true (I deleted the tag and the draft release) 
  * For secret : 
    * GITHUB_TOKEN is already injected by Github Action
    * Could you please import what is needed for GPG Key : 
      * Example for integration : https://github.com/goreleaser/goreleaser-action#signing
      * As the GPG key is already in secret.gpg.enc, I think you just have to import PASSPHRASE (example in SIGN_PASS)

**Comment by kvz** [comment]
Hey Etienne, I added:

- [x] TRANSLOADIT_AUTH_KEY
- [x] TRANSLOADIT_AUTH_SECRET
- [x] GPG_PRIVATE_KEY
- [ ] ~PASSPHRASE~ I do not believe we had one

**Comment by Etienne-Carriere** [comment]
CI : As I made a test with wrong credentials, it seems that templatebasic411 & templatebasic410 were created. Could you delete them ? 
Release: 
* Action : https://github.com/transloadit/terraform-provider-transloadit/actions/runs/1094306722
* Can you confirm me that the GPG_KEY is without passphrase ?

**Comment by Etienne-Carriere** [comment]
I don't find the solution for specific configuration on GPG_PRIVATE_KEY. 
Would it be possible that you change the secret by having  ? 
*  GPG_PRIVATE_KEY with a PASSPHRASE protecting the private key
*  PASSPHRASE for the private key

**Comment by kvz** [comment]
I re-added the GPG_PRIVATE_KEY, this time exporting with --armor and reran the job, seems to have worked now: https://github.com/transloadit/terraform-provider-transloadit/runs/3238248158?check_suite_focus=true

sorry for the long wait on this one, i'm on holidays and having to manage my time a little bit with the family

**Comment by kvz** [comment]
> it seems that templatebasic411 & templatebasic410 were created. Could you delete them ?

Removed these 👌

**Comment by Etienne-Carriere** [comment]
> 
> 
> I re-added the GPG_PRIVATE_KEY, this time exporting with --armor and reran the job, seems to have worked now: https://github.com/transloadit/terraform-provider-transloadit/runs/3238248158?check_suite_focus=true
>
Yes I confirm it is ok !  
> sorry for the long wait on this one, i'm on holidays and having to manage my time a little bit with the family

No problem ! I was just doing the change of CI as I am quite quiet currently ...

**Comment by kvz** [comment]
👍 awesome Etienne! I'm increasingly distancing myself from work. Next two weeks I should not be around. I'm back 23rd Aug. Thanks for all the pushes here!
