### ISSUE TITLE
Template Credentials Resource

### ISSUE THREAD

**Issue by Kaelten** [transloadit/terraform-provider-transloadit#32]
I plan to manage transloadit's iam credentials with terraform.  As it stands I think that means I'd need to embed the credentials in the template config.  It'd be superior if I could create the third-party credentials via terraform so no one needs to know the credentials directly.

**Comment by kvz** [comment]
Agreed!
 
@tim-kos do we have an api endpoint for this already?

**Comment by kvz** [comment]
It seems we do not have Template Credentials support with our API, so that would be the first step before the Terraform provider could be updated to support that as well.

We first need to take a step back and consider if it is even desirable to support automation here. I think it is, but i don't want to risk an oversight on my part. 

Just wanted to update you already and let you know this feature request may take some more time.

**Comment by kvz** [comment]
Hi Bryan just to follow up, there is a basic endpoint in our api for the credentials. I [played](https://github.com/transloadit/node-sdk/pull/141) around with it but there are still some pieces missing, as well as internal discussion to be had about the final interface. It will take some more time to get it :100: I'm thinking weeks not months though.

**Comment by kvz** [comment]
The changes to the Credential API are live now so we can roll this out in the Go SDK

**Comment by Acconut** [comment]
> we can roll this out in the Go SDK

Will @Etienne-Carriere take on this as they already started https://github.com/transloadit/go-sdk/pull/32?

**Comment by Kaelten** [comment]
Seems like things are making good progress.  Any word on when we'll see this in the provider?

**Comment by Etienne-Carriere** [comment]
@Kaelten , just release 0.6.0 version. Documentation for new resource : https://registry.terraform.io/providers/transloadit/transloadit/latest/docs/resources/template_credential

**Comment by Kaelten** [comment]
Was able to adopt it today! Thanks!

**Comment by Missing-Tech** [comment]
Hi @Kaelten! We're currently in the process of writing a blog post about this use-case. Is it alright if we quote a few of your points from this issue (and also send you a draft of the blog post before it's released for your review)?

**Comment by Kaelten** [comment]
> Hi @Kaelten! We're currently in the process of writing a blog post about this use-case. Is it alright if we quote a few of your points from this issue (and also send you a draft of the blog post before it's released for your review)?

Not a problem at all.  Feel free to email it to me, you guys should have my work address on file. :)

**Comment by kvz** [comment]
> Not a problem at all. Feel free to email it to me, you guys should have my work address on file. :)

Tried finding you by company name, surname, handle, but no matches 🤷 also tried twitter, li, & friends, but no dice :) can you please ping joseph@transloadit.com?
