### ISSUE TITLE
Provider param for transloadit_template_credential

### ISSUE THREAD

**Issue by linkyndy** [transloadit/terraform-provider-transloadit#35]
Appreciate creating `transloadit_template_credential` for providing template credentials via Terraform. However, I am missing the link between these credentials and the account/app. Should there be a `provider` param, similar to how `transloadit_template` works?

**Comment by kvz** [comment]
@Etienne-Carriere could you have a look at this?

**Comment by Etienne-Carriere** [comment]
Hello @linkyndy ,

I am not sure to correctly understand your point : 
* You need a `provider` even if it is empty to manage transloadit* resources 
* As you can see in the [doc](https://registry.terraform.io/providers/transloadit/transloadit/latest/docs/resources/template_credential), after creating the credential, you have to reference it in your step in the credentials parameter (doc reference for the action : https://transloadit.com/docs/transcoding/)

Example : 
```hcl 
provider "transloadit" {

}

resource "transloadit_template_credential" "s3" {
  name = "S3_CREDENTIALS"
  type = "s3"
  content = <<EOT
  {
    "bucket" : "mybucket",
    "bucket_region" : "us-east-1",
    "key" : "mykey",
    "secret" : "mysecret"
   }
EOT
}

resource "transloadit_template" "my-terraform-template" {
    name     = "my-terraform-template"
    template = <<EOT
{
  "steps": {
    ":original": {
      "robot": "/upload/handle"
    },
    "exported": {
      "use": [ ":original", "encoded", "thumbed"], 
      "credentials": "${transloadit_template_credential.s3.name}",
      "robot": "/s3/store"
    }
  }
}
EOT
}
```

**Comment by linkyndy** [comment]
@Etienne-Carriere thanks for your reply. That's true, however credentials are stored under some Transloadit account, right? If I go to the dashboard to manually add credentials, I do that under an account. I suspect that your example above will create all credentials under the "default" provider and thus won't make them available in templates that are nested under a different account/have a different provider.

**Comment by kvz** [comment]
I think Andrei manages many Apps (or Workspaces if you will). Each of those has their own credentials. So he creates one Provider per App. And then wants to pass that provider to all the resources so that they belong to the correct Apps. Correct?

**Comment by kvz** [comment]
I do think you already use many resources and they all support passing along the provider, and it is just the new Template Credential provider that does not support it yet?

**Comment by Etienne-Carriere** [comment]
OK. In this case, you can use https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations : 
```hcl
provider "transloadit" {
  auth_key    = "key1"
  auth_secret = "secret1"
  alias = "app1"
}

provider "transloadit" {
  auth_key    = "key2"
  auth_secret = "secret2"
  alias = "app2"
}

resource "transloadit_template_credential" "s3" {
  name = "S3_CREDENTIALS"
  type = "s3"
  content = <<EOT
  {
    "bucket" : "mybucket",
    "bucket_region" : "us-east-1",
    "key" : "mykey",
    "secret" : "mysecret"
   }
EOT
  provider = transloadit.app2
}
```

@kvz , as the environment variable are fixed to TRANSLOADIT_AUTH_KEY / TRANSLOADIT_AUTH_SECRET, it is not practical for users to manage many "App/Workspace"
One solution could be to implement a toml file the .aws/credentials with profile . It could be a .transloadit/credentials

**Comment by linkyndy** [comment]
That's correct, @kvz. 

@Etienne-Carriere didn't know `provider` was readily available inside `transloadit_template_credential`; that's awesome!

**Comment by kvz** [comment]
Thanks Etienne! 👍  

Does this mean we can close the issue Andrei?

**Comment by linkyndy** [comment]
I think so, @kvz. Haven't tried it yet, but I will come back if something doesn't feel right.
