### ISSUE TITLE
Marking template credentials content as sensitive

### ISSUE THREAD

**Issue by linkyndy** [transloadit/terraform-provider-transloadit#40]
Is there a way to mark a template credential's content as sensitive? Or, at least they key/secret pair? Doing a `terraform plan` will show the values in plain text, which isn't something desired.

**Comment by kvz** [comment]
@Etienne-Carriere could you have a look?

**Comment by Etienne-Carriere** [comment]
@kvz, I proposed a PR for that

**Comment by Etienne-Carriere** [comment]
Version 0.7.0 is released with the feature (https://registry.terraform.io/providers/transloadit/transloadit/latest) . @linkyndy, please close the issue if ok for you.

**Comment by linkyndy** [comment]
Looks great, thank you! 🙏
